name: fitbitter
description: A Flutter package to make your life easier when dealing with Fitbit APIs.
version: 2.0.6
homepage: https://github.com/gcappon/fitbitter
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_auth_2: ^4.1.0
  dio: ^5.8.0+1 # better web browser
  logger: ^2.5.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
